### ISSUE TITLE
(WR.10.10) Create Quiz Form 

### ISSUE THREAD

**Issue by fishwickid** [fishwickid/team_project_01#5]
Create a series of questions which we will user to suggest to the user which wine is better suited for their evening. Ex...

What type of food will you like to have (a) Burgers  (b) Thai. (c) Pizza (d) Chinese

**Comment by sukediz** [comment]
Barbecue >> Red >> Malbec
Barbecue >> White >> Rosé
Burgers >> Red >> Cabernet Sauvignon
Burgers >> White >> Oaked Chardonnay
Chinese >> Red >> Blaufränkisch / Gamay
Chinese >> White >> German Riesling
Fried Food >> Red >> Lambrusco
Fried Food >> White >> Champagne
Indian >> Red >> Syrah
Indian >> White >> German Riesling
Italian >> Red >> Chianti (Sangiovese)
Italian >> White >> Pinot Grigio
Pizza >> Red >> Barbera
Pizza >> White >> Grüner Veltliner
Salad >> Red >> Pinot Noir
Salad >> White >> Sauvignon Blanc
Sushi >> Red >> Pinot Noir
Sushi >> White >> Chenin Blanc
Thai >> Red >> Gamay
Thai >> White >> Gewürztraminer
Wings >> Red >> Zinfandel
Wings >> White >> Champagne
